
# 1, number of words (Shaked)
# 2. nuber of tokens (Shaked)
# 3. number of sentences/rows (Shaked)
# 4. sub-repetitions in the corus (Ariel)
# 5. repetitions of words in the paragraphs(yeah yeah yeah) (Ariel)
# 6. rhymes checking (Ariel)
# 7. number of unique words (Shaked)
# 8. precision and recall (Tomer)
# 9. single chorus in the song (Tomer)